### ISSUE TITLE
活塞原理抓虫

### ISSUE THREAD

**Issue by Fallen-Breath** [kaniol-lck/Minecraft-Note#1]
文章写得真的很详细很用心，先给飞飞点个赞！

-------

1. 将 `setBlockState` 传入参数的 flags 的第 6 位表述为 "放置移除更新" 我认为不妥，因为这个 bit 不仅仅在 `onPlace` 中会使用，在 `onRemove` 中也会使用并会将此参数继续传递至其他方法中。这个 bit 是在 1.13 中新增的，个人推测是 mojang 尝试~~胡乱~~抑制方块更新以移除活塞相关的复制

2. https://github.com/kaniol-lck/Minecraft-Note/blob/4f5cc464ea3e4d07fa3685ca90a035c44cef7fce/Piston/PistonBaseBlock.java#L45-L47

这个冗长的 if 可以整理为如下

```java
if (
	blockState2.is(Blocks.MOVING_PISTON) &&
	blockState2.getValue(FACING) == direction && 
	(blockEntity = level.getBlockEntity(blockPos2)) instanceof PistonMovingBlockEntity && 
	(pistonMovingBlockEntity = (PistonMovingBlockEntity)blockEntity).isExtending() && 
	(
		pistonMovingBlockEntity.getProgress(0.0f) < 0.5f || 
		level.getGameTime() == pistonMovingBlockEntity.getLastTicked() ||
		((ServerLevel)level).isHandlingTick()
	)
)
```

前三行与 `如果这个方块是朝向与当前活塞同向推出的b36方块` 相符，但是最后一个由 `||` 组成的析取式的含义并非 `且这次更新不为b36方块的到位更新`。这个子式的值为 `false` 还可由恰当时刻在实体阶段触发的更新实现

3. https://github.com/kaniol-lck/Minecraft-Note/blob/main/Piston/README.md#更新顺序 本段最后一行，“更新顺序随机”用“更新顺序依赖于方向位置”可消除随机一次无指代的歧义，就如 https://github.com/kaniol-lck/Minecraft-Note/blob/main/Piston/README.md#亮起侦测器的移除运算 最后一行一样

4. https://github.com/kaniol-lck/Minecraft-Note/blob/main/Piston/README.md#失活的珊瑚珊瑚扇的掉落 最后一行，铁轨可附着于移动完成的上表面完整的 b36 方块上

**Comment by kaniol-lck** [comment]
感谢抓虫！这些建议都非常的严谨，我会去修改文章中的问题。

1. 此处的放置移除更新确实是表述错误，在编辑过程中同步出了点问题（这还是最开始看的时候错误认为的），应是抑制了部分方块的放置移除运算，传递到其他方法中似乎只有铁轨放置到无效方块时的移除会用到这个bit位，同样传递了第六位的置为情况，没看到有其他的用途。
2. 确实漏掉了实体阶段也不处于`handlingTick`中。我觉得麻将的本意就是排除b36的到位更新，不懂为什么会把这一实体产生的包含进来，还是不太理解麻将（
